

CORBON_LAYOUT="two-line"

CORBON_LEFT="context path git"
CORBON_RIGHT="python node duration time"

CORBON_SEPARATOR="  "

CORBON_PROMPT_SYMBOL="❯"
CORBON_CONTINUATION_SYMBOL="·"


CORBON_SHOW_USER=true
CORBON_SHOW_HOST="ssh"



CORBON_PATH_STYLE="smart"
CORBON_PATH_MAX=4
CORBON_PATH_TRUNCATE="…"



CORBON_GIT_BRANCH=true
CORBON_GIT_STATUS=true
CORBON_GIT_AHEAD_BEHIND=true

CORBON_GIT_CLEAN_SYMBOL="✓"
CORBON_GIT_DIRTY_SYMBOL="±"
CORBON_GIT_STAGED_SYMBOL="+"
CORBON_GIT_UNTRACKED_SYMBOL="?"
CORBON_GIT_CONFLICT_SYMBOL="!"



CORBON_SHOW_EXIT=true

CORBON_SHOW_DURATION=true
CORBON_DURATION_THRESHOLD=1

CORBON_SHOW_TIME=false
CORBON_TIME_FORMAT="%H:%M"


CORBON_COLOR_USER="%F{white}"
CORBON_COLOR_HOST="%F{cyan}"
CORBON_COLOR_PATH="%F{245}"

CORBON_COLOR_GIT="%F{yellow}"

CORBON_COLOR_SUCCESS="%F{green}"
CORBON_COLOR_ERROR="%F{red}"

CORBON_COLOR_MUTED="%F{242}"
CORBON_COLOR_ACCENT="%F{yellow}"

CORBON_RESET="%f"